### PR TITLE
Add initial CSS tooling

### PR DESCRIPTION
**Pull request by jasonlong**
I haven't done much work on git-scm since the new design shipped three years ago, but I'd like to do some serious cleanup and refactoring of the CSS.

This first pull adds a Gruntfile for running [Parker](https://github.com/katiefenn/parker). This generates a Markdown file with CSS stats and this file gets checked in under the `docs` folder. Currently, this is not automated and needs to be done manually. This is mainly for my needs right now, so that shouldn't be a big deal.

To get the Parker grunt task working, I needed to rename the `.css.scss` files to just `.scss`. I also needed to remove the Compass dependency which is something I wanted to do anyway. 

Also, I noticed that the production CSS file includes debug line numbers. I turned on `config.assets.css_compressor = :sass` in the `production.rb` config, but I'm not 100% sure that'll fix the problem. Not sure if there's a precompile deployment task we can run? This alone will put a big dent in our asset bundle.

Oh, and I optimized the new book cover PNG.

I'm not sure what the testing / deployment process is like these days, but hopefully this can be tested on a staging server. Please let me know what I can do to help. After this, I will have a bunch of cleanup PRs coming. :sparkles:

### CODE REVIEW

**Comment by bry4n** [comment]
Parker sounds cool! I'll setup staging server to test this change. Let you know if I run into any issue.

**Comment by jasonlong** [comment]
Thanks @bry4n. I've got a series of pulls coming after this, so it'll be nice to have some before/after metrics.

**Comment by jasonlong** [comment]
Hey @bry4n, just seeing if you've had a chance to work on the staging server yet. Anything I can do to help out?

**Comment by bry4n** [comment]
Sorry, things were hectic on my end. I did look at this and setup heroku for this. I'll check again today.

**Comment by bry4n** [comment]
@jasonlong 

https://gitscm-staging.herokuapp.com/ 

I have pushed this pull request to staging site. I didn't see any errors so far. Let me know if you see any CSS errors. :ok_hand:

**Comment by jasonlong** [comment]
Awesome, thx @bry4n.

**Pull request merged**
