### PR TITLE
Update ruby dependencies

### PR DESCRIPTION
**Pull request by tarebyte**
I was trying to replace with a different Elasticsearch client since it was out of date, but I ended up running into bundler issue with things being out of date.

This just updates the current dependencies.

### CODE REVIEW

**Comment by pedrorijo91** [comment]
thanks a lot for the contribution @tarebyte !

LGTM, just giving some time if anyone has something more to say before merging

**Comment by pedrorijo91** [comment]
The heroku build failed https://dashboard.heroku.com/apps/git-scm/activity/builds/46384160-f79b-49e8-b685-53ffb67a9f72

Just reverted at #1152 . Will try to see why it failed, fix, and redo this PR

**Comment by pedrorijo91** [comment]
any hint why the deploy may be failing @tarebyte? Not an expert on ruby/rails

```
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.4.2
-----> Installing dependencies using bundler 1.15.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Fetching gem metadata from https://rubygems.org/........
       Fetching version metadata from https://rubygems.org/..
       Fetching dependency metadata from https://rubygems.org/.
       Fetching rake 12.3.0
       Using concurrent-ruby 1.0.5
       Fetching minitest 5.11.3
       Using thread_safe 0.3.6
       Using builder 3.2.3
       Using erubis 2.7.0
       Using mini_portile2 2.3.0
       Fetching crass 1.0.3
       Installing minitest 5.11.3
       Installing rake 12.3.0
       Installing crass 1.0.3
       Using rack 1.6.8
       Fetching mini_mime 1.0.0
       Installing mini_mime 1.0.0
       Using arel 6.0.4
       Fetching public_suffix 3.0.2
       Using ansi 1.5.0
       Using asciidoctor 1.5.6.1
       Using bundler 1.15.2
       Fetching chunky_png 1.3.10
       Using coffee-script-source 1.12.2
       Using execjs 2.7.0
       Using thor 0.19.4
       Installing public_suffix 3.0.2
       Using fssm 0.2.10
       Using sass 3.2.19
       Using diff-lcs 1.3
       Fetching unf_ext 0.0.7.5
       Installing chunky_png 1.3.10
       Using multipart-post 2.0.0
       Using hashr 0.0.22
       Using hike 1.2.3
       Fetching iso8601 0.10.1
       Installing iso8601 0.10.1
       Installing unf_ext 0.0.7.5 with native extensions
       Using json 2.1.0
       Fetching kgio 2.11.2
       Installing kgio 2.11.2 with native extensions
       Using mime-types 2.99.3
       Fetching multi_json 1.13.1
       Installing multi_json 1.13.1
       Using netrc 0.11.0
       Fetching pg 1.0.0
       Installing pg 1.0.0 with native extensions
       Using rack-timeout 0.4.2
       Using tilt 1.4.1
       Using rails_serve_static_assets 0.0.5
       Using rails_stdout_logging 0.0.5
       Using raindrops 0.19.0
       Using redcarpet 3.4.0
       Using redis 4.0.1
       Using rubyzip 1.2.1
       Using yajl-ruby 1.3.1
       Fetching i18n 0.9.5
       Installing i18n 0.9.5
       Fetching tzinfo 1.2.5
       Installing tzinfo 1.2.5
       Fetching nokogiri 1.8.2
       Installing nokogiri 1.8.2 with native extensions
       Using rack-test 0.6.3
       Fetching mail 2.7.0
       Installing mail 2.7.0
       Using coffee-script 2.4.1
       Fetching uglifier 4.1.6
       Installing uglifier 4.1.6
       Using addressable 2.5.2
       Fetching faraday 0.14.0
       Installing faraday 0.14.0
       Using compass 0.12.7
       Using unf 0.1.4
       Fetching sprockets 2.11.0
       Installing sprockets 2.11.0
       Using rails_12factor 0.0.3
       Using redis-store 1.4.1
       Using activesupport 4.2.10
       Fetching unicorn 5.4.0
       Installing unicorn 5.4.0 with native extensions
       Using launchy 2.4.3
       Using faraday_middleware 0.12.2
       Using sawyer 0.8.1
       Using compass-rails 2.0.0
       Using domain_name 0.5.20170404
       Fetching redis-rack 2.0.4
       Installing redis-rack 2.0.4
       Using rails-deprecated_sanitizer 1.0.3
       Using globalid 0.4.1
       Using activemodel 4.2.10
       Using redis-activesupport 5.0.4
       Fetching octokit 4.8.0
       Installing octokit 4.8.0
       Using http-cookie 1.0.3
       Using activejob 4.2.10
       Using activerecord 4.2.10
       Using rest-client 1.8.0
       Using tire 0.6.2
       Fetching rails-dom-testing 1.0.9
       Fetching loofah 2.2.0
       Installing rails-dom-testing 1.0.9
       Installing loofah 2.2.0
       Using rails-html-sanitizer 1.0.3
       Using actionview 4.2.10
       Using actionpack 4.2.10
       Using actionmailer 4.2.10
       Using railties 4.2.10
       Using sprockets-rails 2.3.3
       Using redis-actionpack 5.0.2
       Using coffee-rails 4.2.2
       Using jquery-rails 4.3.1
       Using rails 4.2.10
       Using sass-rails 4.0.3
       Using redis-rails 5.0.2
       Bundle complete! 41 Gemfile dependencies, 88 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Bundle completed (35.64s)
       Cleaning up the bundler cache.
       Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Removing pg (0.21.0)
       Removing nokogiri (1.8.1)
       Removing public_suffix (3.0.0)
       Removing octokit (4.7.0)
       Removing minitest (5.10.3)
       Removing unf_ext (0.0.7.4)
       Removing uglifier (3.2.0)
       Removing tzinfo (1.2.4)
       Removing chunky_png (1.3.8)
       Removing loofah (2.1.1)
       Removing faraday (0.13.1)
       Removing rake (12.2.1)
       Removing i18n (0.9.0)
       Removing iso8601 (0.9.1)
       Removing unicorn (5.3.1)
       Removing mail (2.6.6)
       Removing multi_json (1.12.2)
       Removing rails-dom-testing (1.0.8)
       Removing redis-rack (2.0.3)
       Removing kgio (2.11.0)
       Removing sprockets (2.11.3)
       Removing crass (1.0.2)
       The latest bundler is 1.16.1, but you are currently running 1.15.2.
       To update, run `gem install bundler`
-----> Installing node-v6.11.1-linux-x64
-----> Detecting rake tasks
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       ** Invoke assets:precompile (first_time)
       ** Invoke assets:environment (first_time)
       ** Execute assets:environment
       ** Invoke environment (first_time)
       ** Execute environment
       ** Execute assets:precompile
       rake aborted!
       Uglifier::Error: Unexpected token: keyword (const). To use ES6 syntax, harmony mode must be enabled with Uglifier.new(:harmony => true).
       (in /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/app/assets/javascripts/application.js)
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/uglifier-4.1.6/lib/uglifier.rb:234:in `parse_result'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/uglifier-4.1.6/lib/uglifier.rb:216:in `run_uglifyjs'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/uglifier-4.1.6/lib/uglifier.rb:168:in `compile'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/uglifier_compressor.rb:25:in `evaluate'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:197:in `block in evaluate'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:194:in `each'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/context.rb:194:in `evaluate'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/bundled_asset.rb:25:in `initialize'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:377:in `new'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:377:in `build_asset'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:94:in `block in build_asset'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/caching.rb:58:in `cache_asset'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:93:in `build_asset'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/base.rb:287:in `find_asset'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/index.rb:61:in `find_asset'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:211:in `block in find_asset'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:257:in `benchmark'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:210:in `find_asset'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:119:in `block in compile'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `each'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/sprockets/manifest.rb:118:in `compile'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-2.11.0/lib/rake/sprocketstask.rb:146:in `with_logger'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
       /tmp/build_9b8b75906e0da727820137a51a96c66c/git-git-scm.com-88e3f33/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
       Tasks: TOP => assets:precompile
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by tarebyte** [comment]
@pedrorijo91 somehow during my bundle update sprockets actually got downgraded https://github.com/git/git-scm.com/pull/1150/files#diff-e79a60dc6b85309ae70a6ea8261eaf95R219 and uglifier when upgraded a major version https://github.com/git/git-scm.com/pull/1150/files#diff-e79a60dc6b85309ae70a6ea8261eaf95R242

So maybe something strange happened where the assets couldn't precompile?

**Comment by pedrorijo91** [comment]
Yes, I've also noticed the uglify change. By fixing the uglify version the update is successful: https://github.com/git/git-scm.com/compare/bump/gems

**Comment by pedrorijo91** [comment]
although it deploys, it crashes in runtime. I saw this from the logs:

`2018-02-25T14:45:44.408103+00:00 app[web.1]: Gem::LoadError: Specified 'postgresql' for database adapter, but the gem is not loaded. Add `gem 'pg'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).
`

**Comment by pedrorijo91** [comment]
I've constrained the `pg` and `uglifier` versions and deployed the branch `bump/gems`, which seems to be working now (https://github.com/git/git-scm.com/compare/bump/gems).  (cc @peff )

probably this is not the best solution and we should investigate how to allow bumping those versions.

* from what I've seen, it may be a problem between `pg` and `active records` versions
* about the uglifier, I didn't try to understand the root cause

**Pull request merged**
