### PR TITLE
Perl website redirects to https

### PR DESCRIPTION
**Pull request by benabbottnz**

### CODE REVIEW

**Comment by pedrorijo91** [comment]
Thanks for the contribution @benabbottnz ! :)

@peff merging this PR. As far as I remember you still need to manually deploy this changes right?

**Comment by peff** [comment]
@pedrorijo91 Thanks. I just hooked up auto-deploys from this repository, so further merges to `master` should get deployed automatically. Remember that there's a caching layer with a 4-hour timeout in front of Heroku, though, so changes may not be visible immediately.

**Comment by pedrorijo91** [comment]
I personally don't like auto deploys, but since I'm not going to merge complex PRs without other reviewers I think it's ok for now :)

**Comment by peff** [comment]
One other option is to give a few people the ability to deploy via heroku (it really is just a `git push`). I'm happy to do that, though my general feeling is that stuff shouldn't get merged to master until we're fairly sure it's in good shape.

**Comment by pedrorijo91** [comment]
yes, in a more complex situation that would probably be the best option (IMHO), but as I said before, for the usual simple cases, this is more than enough for now

**Pull request merged**
