### PR TITLE
Make download commands look like root

### PR DESCRIPTION
**Pull request by betseg**
The `$`s might be confusing.

### CODE REVIEW

**Comment by KubaKaszycki** [comment]
I agree. All installation instructions, everywhere on the Net, should use `#`s.

**Comment by peff** [comment]
Sorry, this PR got overlooked. It does seem like a reasonable change. Should the `cd` in the FreeBSD instructions use it, too (obviously you don't need to be root to `cd`, but clearly it should be done in the same root shell).

**Comment by sxlijin** [comment]
I tend to defer to Arch wiki convention here, which is to only `sudo` a command if warranted, and that `$` indicates non-`sudo`, whereas `#` indicates `sudo`.

**Comment by peff** [comment]
@sxlijin Do you mean with respect to the `cd`, which doesn't need a `sudo`? If that's the case, the problem resolved itself. :wink: If you look at the merge commit, that line changed in another branch to use the `pkg` command directly, and so the question went away entirely.

**Comment by sxlijin** [comment]
Yep :) and I did notice that, I just mentioned it because of your closing comment.

**Pull request merged**
