### PR TITLE
Updated README.md - misspelled word

### PR DESCRIPTION
**Pull request by justinpinili**
Originally said "man pages" on line 20, when in actuality I think you mean "main pages".

### CODE REVIEW

**Comment by sutiam** [comment]
@justinpinili I guess you're a Windows guy, right? `man page` as described in this [wiki article](http://en.wikipedia.org/wiki/Man_page) is a UNIX term for software docs, it's __NOT__ a typo, and there's no need to change it.

**Comment by izhencalvin** [comment]
Sent from Samsung Mobile.

**Comment by izhencalvin** [comment]
--
Sent from myMail app for Android

**Comment by izhencalvin** [comment]
Jomar

Sent from Yahoo Mail on Android

**Pull request closed without merging**
