### PR TITLE
Added license info

### PR DESCRIPTION
**Pull request by MisterBiggs**
Added license info for a GUI Clients that are free and has the license
listed.

### CODE REVIEW

**Comment by pedrorijo91** [comment]
There's another PR tackling this issue: https://github.com/git/git-scm.com/pull/1030

There's a discussion about if this is the way we want to go as you can see in the comment: https://github.com/git/git-scm.com/pull/1030#issuecomment-335030069

**Comment by MisterBiggs** [comment]
Awesome thanks!

**Comment by peff** [comment]
@MisterBiggs I'd love it if you could review #1030; any place where you two ended up with the same value would give us confidence (and anywhere you diverged is worth looking into).

**Comment by MisterBiggs** [comment]
I'll definitely take a gander!

**Pull request closed without merging**
