### PR TITLE
Blog post fix

### PR DESCRIPTION
**Pull request by radistao**
@peff @slopes321
Please review and accept, if it matches, my fixes for wrong commit images and references in the text for git _Undoing Merge_ blog post.

### CODE REVIEW

**Comment by peff** [comment]
The changes are more extensive here than I expected; I thought we just needed to give a new number to the duplicate C8. Not that changing more is necessarily wrong, but what made you decide to renumber the other commits?

**Comment by radistao** [comment]
I just wanted to keep all images consistent: all commits now looks in expected time order  and all images have the same basic root pattern (`1->2->3->4->5`), which looks better, than (`1->2->15->4->5`). 

Basically, at first i made those images with "new number" 13. Than i understood, that 13 is used on other images and I should use some unique number (> 14 in our case). Then i looked at the images and understood, it is confuses, why 15 is between 2 and 8. So, finally i decided if change something - change it to be good completely, not just a t crutch.

That's it...

**Comment by peff** [comment]
Thanks for explaining. I guessed it was something along those lines, but wanted to be sure.

I gave a brief read-through of the content and AFAICT the updates are all sane. Thanks for working on this. I'm sure the image-tweaking was a bit tedious. :)

**Comment by radistao** [comment]
yeah, especially in tricky GIMP :)

**Comment by radistao** [comment]
guess now #830 may be closed as well?

**Pull request merged**
