### PR TITLE
Update ext.html.erb

### PR DESCRIPTION
**Pull request by packtpartner**
I have updated the listing in the books section

### CODE REVIEW

**Comment by pedrorijo91** [comment]
for traceability, the previous iterations on this PR are available at:

* https://github.com/git/git-scm.com/pull/1090
* https://github.com/git/git-scm.com/pull/1088
* https://github.com/git/git-scm.com/pull/1087
* https://github.com/git/git-scm.com/pull/1086

**Comment by pedrorijo91** [comment]
on https://github.com/git/git-scm.com/pull/1086 you updated a book cover. don't you want to introduce that change also?

**Comment by pedrorijo91** [comment]
@peff is the page https://git-scm.com/doc/ext being cached? while locally I get the new changes, in production they don't appear even with hard reload or incognito mode.

**Comment by peff** [comment]
@pedrorijo91 Yes, there's caching at the CDN level that doesn't even hit the backend servers (since the load as such a problem). You can hit the Heroku site directly if you want to bypass teh cache (e.g., https://git-scm.herokuapp.com/doc/ext, which shows the change).

**Comment by pedrorijo91** [comment]
nice :) what's the cache invalidation policy? do we want to enforce revalidation in some cases (this is probably just a minor change that can wait a bit until it is shown, but we may have others more urgent) ?

**Comment by peff** [comment]
It's a 4-hour cache. I can manually invalidate specific pages (or the whole cache) manually by logging into cloudflare. Unfortunately at our tier of service they don't have good support for having multiple users admin the system.

**Comment by jnavila** [comment]
Ah. That's the rebuild of the book was still showing some internal link errors. :relieved:

**Pull request merged**
