### PR TITLE
Add instructions to access API with 2FA

### PR DESCRIPTION
**Pull request by pedrorijo91**
Add more information on how to access the API with password for users with 2FA enabled, using Personal Access Tokens

### CODE REVIEW

**Comment by peff** [comment]
I think this is fine, but I'd expect most people to use the `local_index` task. It's much faster.

**Comment by pedrorijo91** [comment]
yes `local_index` for the man pages, but the `remote_genbook`  task requires access to API. I tried without credentials but I got a 403 Too many requests immediately.

**Comment by peff** [comment]
Ah, right. I wonder if it would be worth having a local variant of the book generation (certainly the image-importing script works off of a local copy). Besides being easier to get running, it would let people preview book changes before they're merged to master.

The local/preindex split for the man pages is a complete mess of duplication, though. If we do add a `local_genbook`, we should make sure that both tasks can share code for the common bits.

**Comment by pedrorijo91** [comment]
agree. maybe we should create an issue so that it can be approached in the near future?

**Comment by peff** [comment]
Sure. I'm not planning to work on it myself, but if you want to create issues as placeholders, I don't mind.

**Pull request merged**
