### PR TITLE
Fix issue #377 - Inconsistent OS listings on Downloads page

### PR DESCRIPTION
**Pull request by fzeeb**
Removed link to Solaris
Changed "Linux" to "Linux/Unix"

### CODE REVIEW

**Comment by peff** [comment]
I like this way better. Since we cover all unix-y variants on the same page, I don't know why there is any reason to call out Solaris as opposed to say, FreeBSD (or IllumOS for that matter :wink:)

Can we drop the Solaris icon png and css rules now, too?

**Comment by pedrorijo91** [comment]
icons at:

* https://github.com/git/git-scm.com/blob/master/public/images/icons/solaris.png
* https://github.com/git/git-scm.com/blob/master/public/images/icons/solaris@2x.png

css/scc rules:

* https://github.com/git/git-scm.com/search?p=1&q=solaris&type=&utf8=%E2%9C%93

There's also a solaris reference at https://github.com/git/git-scm.com/blob/8d9f73892a06fdf9cb803abb65cb0f4e49b26d4c/app/views/downloads/installers/index.html.haml

**Comment by peff** [comment]
Mentioning Solaris is fine on that installers page. I just don't think it deserves a spot in the Mac/Windows/Unix list of platforms.

I must admit I am scratching my header over that installers page, though. Is it actually accessible from the site? I couldn't find it.

**Comment by pedrorijo91** [comment]
I didn't try a lot, but couldn't find it neither. /downloads/installers redirects to /downloads
but as I said, didn't go through the code with enough detail to be sure

the other files on that folder appear as list under Downloads at https://git-scm.com/download/ but installers no, so I doubt it's used

**Comment by peff** [comment]
@fzeeb I see you dropped the pngs and css. Thanks!

I think it may be worth cleaning up that installers page (after confirming that it's not actually reachable), but that's a totally separate topic.

**Pull request merged**
