### PR TITLE
Added CodeReview GUI client

### PR DESCRIPTION
**Pull request by FabriceSalvaire**
See https://github.com/FabriceSalvaire/CodeReview/

### CODE REVIEW

**Comment by pedrorijo91** [comment]
@FabriceSalvaire would you be interested in rebasing your PR to include CodeReview on the list of  GUI clients?

**Comment by FabriceSalvaire** [comment]
Yes, you want a new PR ?

**Comment by pedrorijo91** [comment]
yes. For some reason when I went through all the issues sometime ago this one missed me. just take into account GUI clients are now ordered through popularity order as determined by Google Trends 12 month view ( #975 )

while I don't think nobody is going to be very picky, at least an effort should be made to keep an approximated order

**Comment by FabriceSalvaire** [comment]
done #1029

**Pull request closed without merging**
