### PR TITLE
Add Gitember to GUI Clients Page

### PR DESCRIPTION
**Pull request by iazarny**
## Changes

-

### CODE REVIEW

**Review by pedrorijo91 — APPROVED** [review]

**Comment by peff** [comment]
Hmm. I have mixed feelings on this one with respect to our [trademark policy](https://git-scm.com/trademark). The name "Gitember" goes against the "portmanteau" discussion there, and the very generic "gitgui.org" domain invites confusion (especially as the project already ships `git-gui`!).

I know we haven't been very consistent about this in the past. We've basically taken any 3rd-party programs that people suggest into the list without doing any real curation, and so we have stuff like `GitUp` there. So I'm not necessarily sure now is the moment to change that, but it's definitely something to consider.

**Comment by pedrorijo91** [comment]
@peff i was not aware of that detail. But I guess 90% of git GUI clients will have `git` written on the name 😅

**Comment by iazarny** [comment]
Request for permission to use Git as part of the Gitember name has been sent to trademark@sfconservancy.org

**Comment by iazarny** [comment]
Gentlemens,  any good news?

**Comment by pedrorijo91** [comment]
closing this PR for now. if you get any updates let us know and we can re-open it @peff  @iazarny (and sorry for your work/PR being caught on this trademark policy issue)

**Pull request closed without merging**
