### PR TITLE
Improve fonts for Linux

### PR DESCRIPTION
**Pull request by felipec**
## Changes

- Cleanups the fonts
- Adds good alternatives for Linux (not just `serif`)

## Context

The current fonts in Linux look horrendous. You can see the exact same issue in git/git.github.io#469, the [original](https://i.imgur.com/IGwT40T.png), and the [improved](https://i.imgur.com/iD4rTv8.png) version.

1. The fallback font should be [sans-serif](https://i.imgur.com/7KXVsQa.png). (so it's at least readable)
2. A good minimum should be [DejaVu Serif](https://i.imgur.com/hVu3VNS.png), which is present in many Linux systems. (this looks close to [Georgia](https://i.imgur.com/J836wnh.png))
3. The best one should be [Roboto Slab](https://i.imgur.com/iD4rTv8.png). (it's very close to [Adelle](https://i.imgur.com/0hLGh8H.png), but it's free, and doesn't cost $540.26 USD)

The [git.github.io](https://git.github.io) site has been running with these for some time.

### CODE REVIEW

**Comment by rimrul** [comment]
>The fallback font should be sans-serif.

The other fonts are all serif fonts. Why should the final fallback be sans-serif?

> In Linux systems typically the first options don't exist, so the page
ends up with 'serif', which is how hello world pages look like.

Times New Roman certainly fits the same description.

> Other systems should not be affected.

I'm inclined to agree for Windows and probably mac OS, but does this hold up for more niche systems? Then again, it might be an improvement for them as well.

**Comment by felipec** [comment]
> > The fallback font should be sans-serif.
> 
> The other fonts are all serif fonts. Why should the final fallback be sans-serif?

Because geometric slab serifs such as Adelle or Roboto Slab are closer to sans-serif fonts than most serif fonts.

According to [Wikipedia](https://en.wikipedia.org/wiki/Slab_serif):

"Some such as Memphis and Rockwell have a geometric design with minimal variation in stroke width: they are sometimes described as sans-serif fonts with added serifs."

> > In Linux systems typically the first options don't exist, so the page
> > ends up with 'serif', which is how hello world pages look like.
> 
> Times New Roman certainly fits the same description.

Times New Roman is typically not installed on Linux systems, but an alias, which at least chromium ignores, so it's a no-op.

It don't know if it does something for Windows or macOS machines. I didn't want to mess with that and minimized the changes. If it was up to me I would just remove Times New Roman.

> > Other systems should not be affected.
> 
> I'm inclined to agree for Windows and probably mac OS, but does this hold up for more niche systems? Then again, it might be an improvement for them as well.

They probably have an open font like DejaVu, and if not, they are probably rendering with `serif`.

**Comment by peff** [comment]
I don't have a strong opinion on this either way, but it kind of makes me wonder if you just have a lousy fallback font for "serif". On my system, it's Liberation Serif, which looks...fine.

Curiously, DejaVu Serif seems to be much larger even at the same font-size. I don't mind it, but it may cause some extra wrapping (look at the navbar in the before/after images you linked, for example).

**Comment by rimrul** [comment]
> > > The fallback font should be sans-serif.
> > 
> > The other fonts are all serif fonts. Why should the final fallback be sans-serif?
> 
> Because geometric slab serifs such as Adelle or Roboto Slab are closer to sans-serif fonts than most serif fonts.
> 
> According to [Wikipedia](https://en.wikipedia.org/wiki/Slab_serif):
> 
> "Some such as Memphis and Rockwell have a geometric design with minimal variation in stroke width: they are sometimes described as sans-serif fonts with added serifs."

Fair enough.

> It don't know if it does something for Windows or macOS machines.

Times New Roman is installed on most Windows systems. It tends to be what those "hello world pages" use on Windows.

>If it was up to me I would just remove Times New Roman.

Can't say I disagree.

> > > Other systems should not be affected.
> > 
> > I'm inclined to agree for Windows and probably mac OS, but does this hold up for more niche systems? Then again, it might be an improvement for them as well.
> 
> They probably have an open font like DejaVu, and if not, they are probably rendering with `serif`.

So it's probably an improvement for them.

**Comment by felipec** [comment]
> I don't have a strong opinion on this either way, but it kind of makes me wonder if you just have a lousy fallback font for "serif". On my system, it's Liberation Serif, which looks...fine.

Again... Fallbacks are **ignored** by chromium. The fallback of Times New Roman on my system is Tinos, which is the top preference of fontconfig: [30-metric-aliases.conf](https://gitlab.freedesktop.org/fontconfig/fontconfig/-/blob/master/conf.d/30-metric-aliases.conf). Not that it matters, because it's ignored.

Tinos is virtually identical to Liberation Serif (as far as I can tell), and looks pretty bad to me.

> Curiously, DejaVu Serif seems to be much larger even at the same font-size. I don't mind it, but it may cause some extra wrapping (look at the navbar in the before/after images you linked, for example).

If all fonts are much larger, I'd say it's Liberation the one that is small, and it's part of the problem.

Moreover, a properly designed site should not have those kinds of issues, and in fact bugs with that nav bar had already been reported **before** the font was updated: check the [image posted by Jakub Narębski](https://user-images.githubusercontent.com/2706/100221357-dbe6f900-2f18-11eb-803a-f8d3ed6d755b.png). See git/git.github.io#463.

But if fixed the layout as well so that doesn't happen any more.

**Comment by felipec** [comment]
> > It don't know if it does something for Windows or macOS machines.
> 
> Times New Roman is installed on most Windows systems. It tends to be what those "hello world pages" use on Windows.

Precisely; so there's no difference between `style="font-family: Times New Roman"`, `style="font-family: serif"`, or `style=""`; it does nothing.

> > They probably have an open font like DejaVu, and if not, they are probably rendering with `serif`.
> 
> So it's probably an improvement for them.

Yeap. Or at least it doesn't hurt.

**Comment by peff** [comment]
> Again... Fallbacks are **ignored** by chromium. The fallback of Times New Roman on my system is Tinos, which is the top preference of fontconfig: [30-metric-aliases.conf](https://gitlab.freedesktop.org/fontconfig/fontconfig/-/blob/master/conf.d/30-metric-aliases.conf). Not that it matters, because it's ignored.

Not on my system (which is a pretty vanilla Debian unstable install).  Both chromium (from the system .deb -- 90.0.4430.212-1) and chrome (from Google's package, same version) display `Times New Roman` using Liberation Serif (it's easy to see by specifying `"Times New Roman", sans-serif` in the css; this shows up as Liberation Serif, but munging the name to `Times New Foo` shows a sans-serif font). Likewise, if we hit the `serif` default on my system, it's Liberation Serif.

> Tinos is virtually identical to Liberation Serif (as far as I can tell), and looks pretty bad to me.

This seems like the crux of it. You don't like the replacement for Times New Roman, nor the default for `serif` on your system.

I don't have much of an opinion either way. After this PR, I get DejaVu Serif on my system. It looks different, but no better or worse to me.

The original design of the site was done by @jasonlong, who has quite a bit of design experience and presumably had some ideas about how everything fit together. But he's busy with other things these days, and I don't think anybody is really paying much mind to the overall visual design of the site.

So small design changes make me concerned we'll grow into a mish-mash of unmatched and inconsistent styles. But it's also possible we'll stumble towards something better overall (I think even Jason was of the opinion that the current visual design looks pretty dated these days).

So I'd probably give this a few days to see if anybody offers more opinions, and then merge unless there's a strong argument not to.

**Comment by felipec** [comment]
> > Again... Fallbacks are **ignored** by chromium. The fallback of Times New Roman on my system is Tinos, which is the top preference of fontconfig: [30-metric-aliases.conf](https://gitlab.freedesktop.org/fontconfig/fontconfig/-/blob/master/conf.d/30-metric-aliases.conf). Not that it matters, because it's ignored.
> 
> Not on my system (which is a pretty vanilla Debian unstable install). Both chromium (from the system .deb -- 90.0.4430.212-1) and chrome (from Google's package, same version) display `Times New Roman` using Liberation Serif (it's easy to see by specifying `"Times New Roman", sans-serif` in the css; this shows up as Liberation Serif, but munging the name to `Times New Foo` shows a sans-serif font).

What is and isn't considered a "fallback" is very convoluted in fontconfig.

If you edit your fontconfig configuration and add this:

```xml
<alias binding="same">
  <family>Times New Roman</family>
  <accept>
    <family>DejaVu Sans Mono</family>
  </accept>
</alias>
<alias binding="same">
  <family>Foobar</family>
  <accept>
    <family>DejaVu Sans Mono</family>
  </accept>
</alias>
```

And open this:
```html
<p style="font-family: Times New Roman, Foobar, sans-serif; font-size: 32px;">Almost before we knew it</p>
```

With a pristine chromium configuration:
```sh
chromium --user-data-dir=/tmp/chromium test.html
```

You would see the result is a sans-serif font. That means chromium dropped both fonts, even though `fc-match Foobar` returns the right font.

Either way, as I said it doesn't matter, because Tinos is identical to Liberation Serif.

> Likewise, if we hit the `serif` default on my system, it's Liberation Serif.

It does not matter. I can delete the package that provides the Tinos font, the result is the same.

> > Tinos is virtually identical to Liberation Serif (as far as I can tell), and looks pretty bad to me.
> 
> This seems like the crux of it. You don't like the replacement for Times New Roman, nor the default for `serif` on your system.

I don't like the default on your system either.

This is what I get with no fontconfig and a pristine chromium profile:

Screenshot_2021-05-18_10-23-30

Is it not how you see it?

And this is with my modifications:

Screenshot_2021-05-18_10-24-37

To my eyes one is perfectly readable and the other makes my eyes sore.

Also, I doubt chromium reads `serif`, which I have manually configured to be DejaVu Serif, but instead I get Tino. I bet the default for "Serif font" is "Times", which shows as "Custom", and when you change it you can select it any more.

> The original design of the site was done by @jasonlong, who has quite a bit of design experience and presumably had some ideas about how everything fit together. But he's busy with other things these days, and I don't think anybody is really paying much mind to the overall visual design of the site.

Does he work primarily on Linux? I bet he us a macOS user, and obviously has Adelle on his system.

> So small design changes make me concerned we'll grow into a mish-mash of unmatched and inconsistent styles.

The font style is used throughout the whole site. Where would it not match?

**Comment by jasonlong** [comment]
> Does he work primarily on Linux? I bet he is a macOS user, and obviously has Adelle on his system.

Yeah, macOS user here. I thought we were getting Adelle from Google Fonts way back in the early days. If so, I see that's no longer an option. I agree that Roboto Slab (if that's what the screenshot above is using) is much better than what is shown today.

If I were starting fresh today, I'd opt to use a system font stack like we used at GitHub (or maybe [Inter](https://rsms.me/inter/)). I'm definitely not very knowledgeable about Linux fonts like @felipec so I'd defer to his expertise there.

**Comment by peff** [comment]
> Is it not how you see it?

It's similar:

liberation

Though the spacing looks better than the one in your screenshot (in my opinion). But like I said, that seems fine to me.

> The font style is used throughout the whole site. Where would it not match?

We use a typewriter font in many places (e.g., throughout the man pages), which needs to look good next to the normal font. For instance, try http://git-scm.com/docs/git#Documentation/git.txt---version versus https://git-scm-pr-1604.herokuapp.com/docs/git#Documentation/git.txt---version. The size difference is noticeable for me (switching between DejaVu and Liberation), though I don't think either one looks particularly better or worse than the other (in one the typewriter bits are smaller than usual, and in the other bigger).

The book content has its own styling (and seems to be sans-serif, though the table-of-contents is in our default serif; arguably we are already in a mish-mash world of styles). They end up side-by-side via the navbar, and the "prev" and "next" links at the bottom of book pages.

**Comment by felipec** [comment]
> It's similar:
> 
> liberation

You get that from a pristine chromium profile with 96 DPI and 100% zoom?

Seems way bigger. Although it's the same font.

> The size difference is noticeable for me (switching between DejaVu and Liberation), though I don't think either one looks particularly better or worse than the other (in one the typewriter bits are smaller than usual, and in the other bigger).

Yeah, but it's not a mish-mash. DejaVu probably looks closer to what macOS users see. It's different, yeah, but different in the good direction: more aligned to what people see in macOS and Windows.

> The book content has its own styling (and seems to be sans-serif, though the table-of-contents is in our default serif; arguably we are already in a mish-mash world of styles).

Yeah, I did notice that, however sans-serif is a good default because it's considered easier to read on screen (see for example: [What’s the most readable font for the screen?](https://thenextweb.com/news/whats-the-most-readable-font-for-the-screen)). If the font-family was `Adelle, sans-serif` I would not have complained, as that's good enough for me to read.

> They end up side-by-side via the navbar, and the "prev" and "next" links at the bottom of book pages.

I could not parse that. Are you saying that the user sees `$base-font-family` right next to `sans-serif`?

If so, that's already happening between normal text and section headings, because `h2` is not changed in the book:

Screenshot_2021-05-20_10-16-46

That discrepancy of fonts in my opinion actually looks good.

However, that screenshot above is with a pristine chromium configuration, which I think maps `sans-serif` to Arial. Arial is mapped to Arimo by fontconfig, and if not found Liberation Sans, which in my opinion doesn't look that good.

If I change the default chromium configuration from "Custom" to "Sans", then that's actually mapped to the system Sans, which via fontconfig becomes DejaVu Sans.

Screenshot_2021-05-20_10-21-29

That to me looks very nice.

We could help our Linux users by doing `DejaVu Sans, sans-serif` in the book so that even unconfigured chromium users see the above, but this is minor style.

My primary concern was readability, and now that's fixed. Thanks.

**Comment by peff** [comment]
> You get that from a pristine chromium profile with 96 DPI and 100% zoom?

Pristine profile and 100% zoom, but my system has 140 DPI.

> I could not parse that. Are you saying that the user sees $base-font-family right next to sans-serif?

Close by on the same page, I meant. For instance, scroll to the bottom of a random book page like https://git-scm.com/book/en/v2/Git-Basics-Git-Aliases. The `prev | next` line is in the base family, for instance. I hadn't noticed that the headers are, as well. It all looks OK to me.

**Review by wonsuchai — COMMENTED** [review]
felipec:fc/fonts

**Comment by felipec** [comment]
> Pristine profile and 100% zoom, but my system has 140 DPI.

With 140 DPI it kinds of looks similar here, but not quite. I have to crank it up to 150 DPI to see the same you see in your screenshot.

Either way, tune to down to 96 DPI (what most people have configured), and let me know if it's readable.

**Pull request merged**
