### PR TITLE
Correct Uzbek language title

### PR DESCRIPTION
**Pull request by ozbek**

### CODE REVIEW

**Comment by jnavila** [comment]
Thanks for correcting the title. I asked @faxriddin how I should write it but obviously, I didn't provide enough context. 

Unfortunately, I am not allowed to push on this repository. So we can just sit and wait for one of the collaborators to merge your fixup.

**Comment by ozbek** [comment]
Thanks @jnavila. 
Let's wait for the maintainers then.

**Comment by ozbek** [comment]
@bry4n: maybe you can help with merging this?

**Comment by bry4n** [comment]
Thanks for correcting titles!

**Pull request merged**
