### PR TITLE
Redirect always book v1 to v2

### PR DESCRIPTION
**Pull request by jnavila**
v1 is no longer supported and we don't want any reference to this edition.

### CODE REVIEW

**Comment by peff** [comment]
Do we still have any translations that are v1-only? If so, what happens after this if somebody visits one?

**Comment by jnavila** [comment]
I don't know if the DB still containing v1 sections. I tested with non existing language and was redirected in the end to English table of content. At least, all languages proposed on the left are v2.

**Comment by jnavila** [comment]
In fact, we removed the script to feed the DB with v1! 495fa43

**Comment by peff** [comment]
Hmm, I'd have thought we wouldn't have any v1 then, since we have several times dropped and regenerated the database to deal with problems. But maybe the last time was before that commit.

At any rate, it does seem like we long ago made the decision not to care about v1, so let's keep going down that road.

**Pull request merged**
