### PR TITLE
Bump ruby version to latest 2.2.x (2.2.27)

### PR DESCRIPTION
**Pull request by pedrorijo91**
Based on #604

### CODE REVIEW

**Comment by pedrorijo91** [comment]
@paladox done upon your work. If you want to review that would be great :)

**Comment by pedrorijo91** [comment]
We can probably bump to ruby 2.3.x or ruby 2.4.x versions, but I don't know how "aggressive" ruby versions bump are, so I decided to go for baby steps :)

**Comment by pedrorijo91** [comment]
any thoughts on this @peff @jnavila @sxlijin ?

**Comment by jnavila** [comment]
So, what's the incentive to change ruby version, now that most of the traffic is cached?

**Comment by pedrorijo91** [comment]
@jnavila I've been looking through stall PRs and decided to redo this one. Maybe we dont' want, and in that case we should close both PRs (I assume newer versions are more performant and have some bug/security fixes, but that shouldn't be a problem for an app like this)

**Comment by jnavila** [comment]
Another issue is that if we have some binary generation in the modules used by the site, the whole upgrade needs the recompilation of them.This cannot be simply done by merging a pull-request. So it's really up to peff to decide whether he can afford to spend more time on this, the incentive not being great.

He already expressed his desire to get rid of all this stuff in favor of static content. This could even be generated on the developper's platform and pushed as-is on the server.

**Comment by jnavila** [comment]
Another issue is that if we have some binary generation in the modules used by the site, the whole upgrade needs the recompilation of them.This cannot be simply done by merging a pull-request. So it's really up to peff to decide whether he can afford to spend more time on this, the incentive not being great.

He already expressed his desire to get rid of all this stuff in favor of static content. This could even be generated on the developper's platform and pushed as-is on the server.

**Comment by pedrorijo91** [comment]
totally understand the point @jnavila. as I said, I was just redoing the old PR. We can drop this if @peff also agrees

**Comment by peff** [comment]
I shared @jnavila's first response: what does this buy us?

The best answer I can come up with is: eventually old ruby versions get EOL'd, and we eventually have to keep up to date. So baby steps towards the most recent versions over time do make some sense to me. If there's not a lot of hassle in doing so, I think we ought to merge this.

I _think_ this really is as simple as merging the PR. The heavy lifting of gem compatibility is all done by bundler, and Heroku runs that automatically on deploy.

One thing I do notice: Heroku [lists 2.2.8](https://devcenter.heroku.com/articles/ruby-support#ruby-versions) as the supported version in the 2.2.x series. Should we be aiming for that rather than 2.2.7?

**Comment by peff** [comment]
I had trouble building 2.2.x on my Debian unstable machine because it needs an older openssl. So I just pushed up some commits that bump us to 2.4.2. It's branch-deployed on the heroku site right now. Seems fine, though I won't be surprised if there's a little-executed code path that has problems.

See also the caveats in https://github.com/git/git-scm.com/pull/1058/commits/b48576fc0d653e5efa7f0ce2b6402d2eb4a7412f, especially about asciidoctor.

**Comment by pedrorijo91** [comment]
nice @peff :)

**Pull request merged**
