### PR TITLE
delete CodeReview in Windows

### PR DESCRIPTION
**Pull request by tasty0tomato**
after so many times of trying to install CodeReview in Windows(python 3.6 3.7 3.8, msvc 14.0 14.1 14.2 and mingw), I think that it is not suitable to put CodeReview under the Windows list.

### CODE REVIEW

**Comment by pedrorijo91** [comment]
Hey @tasty0tomato, I understand your frustration, but I believe this may be a case of an application just needing to improve the installation process (by providing a packaged executable maybe?). 

I see that you have raised  https://github.com/FabriceSalvaire/CodeReview/issues/49, let's wait and see. I could find other users complaining of the installation process as well (e.g. https://github.com/FabriceSalvaire/CodeReview/issues/45)

but let's be fair, the author did his best to create a useful tool :) he may lack the time to improve it further. we can embrace the OSS spirit by offering help to improve his project.

I'm going to close this issue if you find the project is completly abandoned/unmaintained, we can re-open it and remove the project from the list

**Comment by tasty0tomato** [comment]
> Hey @tasty0tomato, I understand your frustration, but I believe this may be a case of an application just needing to improve the installation process (by providing a packaged executable maybe?).
> 
> I see that you have raised [FabriceSalvaire/CodeReview#49](https://github.com/FabriceSalvaire/CodeReview/issues/49), let's wait and see. I could find other users complaining of the installation process as well (e.g. [FabriceSalvaire/CodeReview#45](https://github.com/FabriceSalvaire/CodeReview/issues/45))
> 
> but let's be fair, the author did his best to create a useful tool :) he may lack the time to improve it further. we can embrace the OSS spirit by offering help to improve his project.
> 
> I'm going to close this issue if you find the project is completly abandoned/unmaintained, we can re-open it and remove the project from the list

I understand it, but I really think that this gui is not for Windows, I tried it in Ubuntu and it succeeded, but never once in Windows.

**Comment by tasty0tomato** [comment]
I kind of want to reopen this issue. I still cannot build it in Windows with the new commit.

**Comment by pedrorijo91** [comment]
sure. Feel free to create a PR to remove the windows availability  (it seems the original repo was deleted so we cannot re-open)

**Comment by FabriceSalvaire** [comment]
@pedrorijo91 your answer is the right one

CodeReview is up to now a personal project, and I only use it on Linux.

I never received any PR and I don't know who is using it etc.

**Comment by pedrorijo91** [comment]
thanks for finding some time too look at the issue @FabriceSalvaire . we all know how hard it can be to maintain an OSS project (specially when it's used across different environment, some of them where we don't even work on regularly). 

maybe you can add some hints on how to improve this known issue on #1614 / https://github.com/FabriceSalvaire/CodeReview/issues/49 , so that affected users can try some workarounds and hopefully add the findings to the project README/FAQ or even submit an improving PR? :)  everyone understands if you lack some time, but at least is a good signal that people are trying to use CodeReview <3 (another solution could be just to invite someone to be a maintainer as well. or just keep it as it is - after all, you are in charge of the project 🙂)

**Pull request closed without merging**
