### PR TITLE
add style to errors

### PR DESCRIPTION
**Pull request by lrn1380**

### CODE REVIEW

**Comment by peff** [comment]
I agree the result looks a little nicer (comparing https://git-scm-pr-1522.herokuapp.com/foo to https://git-scm.com/foo, for example).

The css file repeats some bits found elsewhere. Is it possible to use scss and/or reuse some of the values defined in other stylesheets?

**Comment by lrn1380** [comment]
> من نتیجه به نظر می رسد بهتر کمی (در مقایسه https://git-scm-pr-1522.herokuapp.com/foo به https://git-scm.com/foo ، به عنوان مثال).
> 
> فایل css برخی بیت ها را در جای دیگر تکرار می کند. آیا می توان از scss استفاده کرد و / یا از برخی مقادیر تعریف شده در صفحه های سبک دیگر استفاده مجدد کرد؟

scss files need to compile

**Comment by peff** [comment]
> scss files need to compile

Yes, but is that a problem? I thought we would precompile everything as part of the deploy step.

**Review by adsingh14 — COMMENTED** [review]
- File `404.html` & `500.html` doesn't need to be change.
- We don't need to define all blocks in `errors.css` and it has to be in **SASS** format.

**Comment by adsingh14** [comment]
It seems like a duplicate of #1316. 
@lrn1380 You took responsibility for both `404` and `500` HTML files. Let me know if you could fix it in a minimal way. :)

@peff I want to work on `422.html` file. Please let me know.

**Comment by adsingh14** [comment]
It seems like a duplicate of # 1316.

**Comment by adsingh14** [comment]
It looks like a duplicate of # 1316.

**Pull request closed without merging**
