### PR TITLE
doc : Update README.md

### PR DESCRIPTION
**Pull request by utkarsh006**
- Updated README.md file of this repo for better readability of users.
- Formatted lines of text.
- Made the information concise to look at.
- Added Contributors section.

## Output Screenshots

Screenshot (218)
Screenshot (219)
Screenshot (220)

### CODE REVIEW

**Comment by utkarsh006** [comment]
@pedrorijo91 Kindly Review this PR.

**Comment by pedrorijo91** [comment]
thanks for the contribution @utkarsh006 

but tbh i'm not sure of the value of these changes (this is obviously just my opinion, others may disagree):

- adding the repo size is relevant for anyone or just noise?
- why hide the setup instructions?
- why hide the contributing section? this one in particular I fear that may be negative: people won't see immediately how to add their own git GUI
- finally, the contributors section is just extra noise as well no?

**Comment by utkarsh006** [comment]
@pedrorijo91 I want to clear your words by saying that all my changes would make repo concise and would help user to increase their readability. No one would like to read huge chunks of text but they will prefer to read it in divisions. Repo size is relevant for contributors. I have merged PR's with this change in open food facts. Thanks for reverting back.

**Comment by utkarsh006** [comment]
@pedrorijo91 Kindly Review.

**Comment by ttaylorr** [comment]
> but tbh i'm not sure of the value of these changes (this is obviously just my opinion, others may disagree):

Thanks for your contribution, @utkarsh006, but I agree with @pedrorijo91. Keeping the sections you've hidden visible is important, and I agree that the contributors section is noise. Let's close this for now.

**Comment by pedrorijo91** [comment]
but many thanks for the initiative @utkarsh006 ! we have a few issues open, and we'd love if you'd like to help us fixing some of them :) if you do, let us know, and we can find some of your interest and provide some guidance 😊

**Pull request closed without merging**
