### PR TITLE
delete CodeReview in Windows

### PR DESCRIPTION
**Pull request by tasty0tomato**
## Changes

- delete  CodeReview GUI in Windows.

## Context

https://github.com/git/git-scm.com/pull/1519

### CODE REVIEW

**Comment by peff** [comment]
So the context here is "many people seem to have trouble actually installing and getting it to run on Windows". I agree that we do a disservice to our users to point them to tools which they aren't likely to be able to successfully use. I don't see strong evidence that this is the case, but we have a pretty low bar to add clients here when people ask. So I'm OK to have a low bar to remove them, too. :wink: And this is just the mention of Windows, not the whole project.
 
The link was originally from @FabriceSalvaire, so I'll ping him in here to see if there's any comment. But absent further discussion, I'd plan to merge this in a few days.

**Comment by tasty0tomato** [comment]
@peff To be honest, I wanted to use or try it on Windows at first. https://github.com/FabriceSalvaire/CodeReview/issues/49.
I know CodeReview is a wonderful tool but I just want to figure out if it can be used on Windows.

**Comment by FabriceSalvaire** [comment]
CodeReview is a Python GUI, thus it should be portable on all platforms, Windows, OSX and Linux.

However, it is not a commercial software, thus the installation on Windows is not plug and play.  This is a well known issue with Python.  And personally, I don't have time to improve that.  It is open source and provided as it is.

**Comment by tasty0tomato** [comment]
Still need help.

**Comment by pedrorijo91** [comment]
hey @tasty0tomato . I think the best place to discuss this would be in https://github.com/FabriceSalvaire/CodeReview/issues/49 to see if the maintainer or anyone in the community can give you some hints. If the maintainer is short on time, maybe asking for help from the python community on some forum (reddit e.g.?) can be useful

**Comment by peff** [comment]
I agree that the best place for further discussion of the technical issues is in the CodeReview repo. But the question here for this PR is: is CodeReview on Windows mature enough (not just running as an app, but the installation and setup process) that we feel comfortable listing it on the page? Or maybe we could be annotating it somehow? I dunno. I don't have a strong opinion either way.

**Pull request closed without merging**
