### PR TITLE
Added TL Locale

### PR DESCRIPTION
**Pull request by severinolorillajr**
Hi @jnavila ,
Had the time so I updated the the files accordingly.
Just need to merge this and update the website.
And this last optional item as well, regarding the
automatic compilation of ebook and pdf via a script for travis-ci.
Cheers!

### CODE REVIEW

**Comment by jnavila** [comment]
You need also to change here:
https://github.com/git/git-scm.com/blob/master/app/views/doc/_translations.html.erb#L43

**Comment by severinolorillajr** [comment]
Updated.

**Comment by severinolorillajr** [comment]
Hi Sir @jnavila .
Thanks for merging my updates.
By the way, I will have someone to verify and check the translations.
Do we have a timeline when we can check the updates at https://git-scm.com/book/en/v2.
Thank you so much for the hard work. Cheers!

**Comment by jnavila** [comment]
The publication script runs once a day.

For the ebooks and pdfs, you can have a look at travis-ci.org and at the script .travis.yml in the progit repo. You'll need to set up the deployment for your repo.

**Comment by severinolorillajr** [comment]
Thanks for the update.. 
Will setup the ebooks and pdfs in a while.

**Comment by severinolorillajr** [comment]
It's already been populated.
https://git-scm.com/book/tl
Got 404 error though, do I need to update the controller or something?

**Comment by jnavila** [comment]
The site is updated with each push to the repo, but the publication scripts for the book only run once a day.

**Comment by peff** [comment]
I just kicked off a `rake remote_genbook2`, so it's being served now (you may still see up to 4 hours of lag from the caching layer, though).

**Comment by ruahtheking** [comment]
Hi @jnavila can I ask for you to merge the work of @severinolorillajr?, btw I'm the supervisor of translation team of Utopian.io and we rewarding contributors via steemblockchain so they may be encourage to contribute more. sadly for @severinolorillajr to be rewarded he needs a merged PR of his contribution.

**Comment by severinolorillajr** [comment]
@peff , thanks for the updates. I already see the translations on the main site. Thank you.

@ruahtheking , thanks for commenting here, but as I have said merging this PR for the actual translations is impossible.. I guess I just have to let this go.

**Comment by jnavila** [comment]
@ruahtheking This PR has been merged. What were you expecting?

**Pull request merged**
