### PR TITLE
remove references to book edition 1

### PR DESCRIPTION
**Pull request by pedrorijo91**
starts solving #1149 

We'll also need to:

* delete from the storage: `delete from books where edition == 2;`
* make sure the `lib/tasks/book.rake`, `lib/tasks/book2.rake`, and possible others, don't re-import the book

### CODE REVIEW

**Comment by pedrorijo91** [comment]
we probably just need to delete the `lib/tasks/book.rake` since `lib/tasks/book2.rake` is already filtering edition 2 books right? (based on code and https://github.com/git/git-scm.com/blob/master/ARCHITECTURE.md)

**Comment by peff** [comment]
I'm not clear on the motivation here. I think there are still several languages for which there is only a 1st edition translation. Is the intent to drop all 1st editions completely, or to keep the ones for which there is no 2nd edition translation?

The latter seems like a much less extreme position. If that's what we're going for, then I think we want to keep `book.rake`. I consider the database here to basically just be a cache. We've had to blow it away enough times (due to bugs, etc), that I think we want to be able to regenerate the site from scratch if necessary.

**Comment by pedrorijo91** [comment]
do we want to point to something soo deprecated as the edition 1 for those languages @peff?  I assumed no from #1140 (in particular https://github.com/git/git-scm.com/issues/1140#issuecomment-367491519)

But if we want, then this PR should be discarded

**Comment by jnavila** [comment]
@pedrorijo91 I was a bit bully in the referred comment. I no longer accept changes to version 1, but it would be a waste to not publish it, even if it's old now. The part of the patch that conceals v1 if v2 is available is good.

**Comment by pedrorijo91** [comment]
Thanks @jnavila. I guess this PR doesn't make much sense then. Will close it

**Comment by peff** [comment]
I don't have a strong opinion either way on it. As a native English speaker, I'm not sure whether somebody who isn't would prefer to see older documentation in their native language, or be pointed to the most up-to-date version in English.

**Pull request closed without merging**
