### PR TITLE
Update ext.html.erb

### PR DESCRIPTION
**Pull request by packtpartner**
Added a new book listing

### CODE REVIEW

**Comment by pedrorijo91** [comment]
please, stop opening new PRs. use the previous one #1086. If you are new to git/github and need any help let us know :)

You are still making the same mistake. Please, read carefully my comments at #1086 (there are 3 comments). There's one quote missing. I added the correct line there, make sure you understand (if you don't, feel free to ask), and apply it.

**Comment by packtpartner** [comment]
Hi Pedro,
Sorry for the inconvenience , may I do a new PR with the following listing at the end of the left column?
Hope the entry is in order.

        <li>
         <a href="https://www.packtpub.com/application-development/git-essentials-second-edition"></a>
         <h4><a href="https://www.packtpub.com/application-development/git-essentials-second-edition>Git Essentials - Second Edition</a></h4>
         <p class='description'>
           By Ferdinando Santacroce
         </p>
        </li>

**Comment by pedrorijo91** [comment]
you are still missing the closing quote on the href attribute. 

where you have:

`<a href="https://www.packtpub.com/application-development/git-essentials-second-edition>`

it should be

`<a href="https://www.packtpub.com/application-development/git-essentials-second-edition">`

**Comment by packtpartner** [comment]
I hope everything else is right. I will update this and create a new PR.

Thanks a lot for the help

**Pull request closed without merging**
