### PR TITLE
Mark current section of the book and reference

### PR DESCRIPTION
**Pull request by Hirse**
To address #1359 this PR adds an "active" class to the current chapter or section.
The active item is currently styled as bold, but I'm not sure that provides enough contrast to the other entries. I experimented with the git-orange, but that looks too much like a missing link then.

image

### CODE REVIEW

**Comment by peff** [comment]
Thanks, this looks really good, and it's nice to see it didn't involve a lot of code.

Using bold looks reasonable to me, but of course I'm actively looking for it, since I wanted to see how the feature looked. :wink: I think it may be enough, though.

**Comment by peff** [comment]
I'm going to merge, because I think this is an immediate improvement, and I like the bolding. But I'm happy to revisit the styling if somebody feels strongly about it.

**Comment by phil-blain** [comment]
It's really weird but it seems to not work consistently for the man pages on my end (Chrome 78, Firefox 65,Safari 11.1.2 ) 

It works for some pages but it doesn't for others...
I go to [git-scm.com/docs](http://git-scm.com/docs), click "git", then click "Topics" -> "git" is not bolded.
I go to [git-scm.com/docs](http://git-scm.com/docs), click "config", then click "Topics" -> "config" *is* bolded.

help, init, clone, add are not bolded.
status, commit, diff are bolded.
reset, rm, mv are not.

I could not find a pattern...

**Comment by peff** [comment]
Hmm. One thing I notice is that the ones that _aren't_ bolded seem to be pages that weren't touched in v2.24.0 (and the ones that were _are_ bolded).  For the ones that weren't touched, they still say "version 2.23" (which IMHO is a minor bug in itself, as it's not clear that you're also looking at the same content for 2.24).

I'm not sure why that would be, though. They should have the same `name`, I'd think. And the code in question would run for both old and new versions. But it might be a lead.

**Comment by Hirse** [comment]
In my dev setup, which is still on 2.23, all pages work correctly.

Did any of the naming change with the update to 2.24?

**Comment by peff** [comment]
> Did any of the naming change with the update to 2.24?

No. All that happened is running `rake preindex`, which pulled in the 2.24 pages. You should be able to reproduce with that (or `rake local_index` after updating your git.git clone)

**Comment by phil-blain** [comment]
Another small hiccup: in the book, when in a "Summary" section at the end of a chapter, the  "Summary" section of *each* chapter is highlighted in the dropdown.

**Pull request merged**
