### PR TITLE
Fix line-height issue for multi-line headings in chapters list.

### PR DESCRIPTION
**Pull request by nhantdn**
Fix line-height issue for multi-line headings in chapters list.

### CODE REVIEW

**Comment by nhantdn** [comment]
Here is the screenshot of the issue:
image

**Comment by peff** [comment]
This looks good to me, comparing before and after results. I don't know CSS well enough to know whether there are any gotchas with moving to a static margin from an increased line height, but it seems pretty straightforward.

**Comment by peff** [comment]
So this is merged and pushed to Heroku, but it doesn't actually seem fixed on the site (whereas it did when I looked at in the dev environment). I'm sure this is something to do with the asset pipeline for css on Heroku, but I don't know anything about this. Any pointers from Heroku experts would be appreciated.

**Comment by peff** [comment]
Ah, nevermind, I found it. The assets need to be precompiled and committed to git (yuck), via `rake assets:precompile && git add public && git commit`.

**Pull request merged**
