### PR TITLE
Adding Greek in the translation-started section.

### PR DESCRIPTION
**Pull request by papantonis**
Adding Greek in the "translation started for" section.

### CODE REVIEW

**Comment by peff** [comment]
The added links themselves look good, but I don't think we are actually pulling in your translation of the book yet, so the links don't yet go anywhere. I'm not sure how to do that right now; the [current procedure](https://github.com/git-scm.com/blob/master/lib/tasks/book2.rake) relies on download the HTML ebook from Atlas, but my understanding is that the Atlas builds are currently broken (see #760 and progit/progit2#625).

**Comment by jnavila** [comment]
This is done. Can be closed.

**Comment by peff** [comment]
I totally forgot about this PR while fixing up the links in #927. I notice this uses the correct "el" ISO language code for Greek (instead of "gr"). Given that the translation project is using `progit2-gr`, though, I don't know that it's that big a deal.

**Comment by jnavila** [comment]
Ah. My bad. "gr" is for the country... The translators didn't warn me against that. Apparently "gr" isn't colliding with another language (could be ancient greek, but who would translate to ancient greek anyway).

**Comment by papantonis** [comment]
Sorry my bad, I hand't checked #927. The underlying reason why the locale is not named "gr" is because it's used for Cyprus as well.
I don't mind renaming the organization to "progit2-el" if you want.

**Comment by pedrorijo91** [comment]
@jnavila how is this PR going? is it blocked by something else? does it need something to unblock? should be merged/closed?

**Comment by jnavila** [comment]
AFAIK, this PR was already merged and greek is available: https://git-scm.com/book/gr/v2

The remaining question was if we should move to the correct ISO code for the language, but that's not a big deal, so it's safe to close this.

**Pull request closed without merging**
