### PR TITLE
chore: improve GitHub templates

### PR DESCRIPTION
**Pull request by HonkingGoose**
## Changes:

- Create pull request template
- Prevent contributors opening empty issues
- Remove old ISSUE_TEMPLATE file that's no longer needed
- Redirect unwanted bug reports with `config.yml` file
- Remove wall of text in templates that used to redirect unwanted stuff
- Use clearer headings for operating system/browser section
- Use clear language
- Capitalize noun Git where it's used
- Fix whitespace and file formatting

## Context:

I think the GitHub templates are due a big upgrade, so I'm taking the liberty to improve the lot. 😄 

The main idea is to redirect unwanted stuff from the GitHub issue create screen, instead of in Markdown comments that nobody will read. The new redirects are way easier, because you can just click a button and go to the right place.
I've made a throwaway repository so you can get a preview of how the issue select screen will look once you merge this PR: https://github.com/HonkingGoose/git-scm-template-preview/issues/new/choose

I think that we should have (and use) templates for all valid contributions, so I'm disallowing empty issues from being opened.

Also we didn't have a pull request template, so I'm making one. 😄 

Feel free to tell me to undo stuff you don't want/care about. 😉

### CODE REVIEW

**Comment by pedrorijo91** [comment]
oh, I was not aware of this feature for PR templates. this has so much potential ! thank you @HonkingGoose

**Comment by HonkingGoose** [comment]
@pedrorijo91 I've setup a throwaway repository with the contents of this PR,  so that you can preview the issue template chooser.

Go to: https://github.com/HonkingGoose/git-scm-template-preview/issues/new/choose to get a "live" preview. 😉

**Comment by pedrorijo91** [comment]
really loving it. can we move the links to the top and the issue templates to the bottom?

imagem

asking because some people will just click on the first button they see without reading the rest. If the first button opens another window they will probably go back and read :D

**Comment by HonkingGoose** [comment]
## On moving links to top, issue templates to bottom

> can we move the links to the top and the issue templates to the bottom?

I have not found a way to change the order.

I suspect GitHub is strict with the order to prevent confusion. If a repository owner can change the order themselves, a contributor would get confused on where to find the wanted contributions.

## GitHub template chooser sorting algo

I think GitHub sorts like this:

1. Issues with a template (sorted alphabetically by `name:` in the `downloads.md` and `ui.md` files)
2. Redirects sorted top-to-bottom as listed in the `config.yml` file.

## Docs for `config.yml` file

GitHub call this functionality the "template-chooser".
You can read the [GitHub docs for the `config.yml` file, configuring the template chooser](https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser)

## On contributors not reading further:

> asking because some people will just click on the first button they see without reading the rest. If the first button opens another window they will probably go back and read :D

I do somewhat agree, that users won't always read the text properly.
But you have the same problem _right-now_ with people not reading the Markdown comments in the issue template.

At least this PR puts the redirects at the point where the user decides whether or not to open a issue: in the issue select screen.
If they're in the wrong place, and understand/read that they're in the wrong place, they can just click the button and go to the proper place to report their problem.

You also reduce the amount of boilerplate in the templates themselves, so valid contributors have less to read through.

**Comment by pedrorijo91** [comment]
it's surely an improvement, totally agree! I just touched the sorting point because we have seen users in the past saying "oh, sorry, I totally ignored the other templates".

For me is good enough to merge, and we can further improve afterwards if we find the need for it

**Review by pedrorijo91 — APPROVED** [review]

**Comment by peff** [comment]
Thanks, this is so much better!

Some random thoughts:

  - I do wish there were more space to explain the situation for some of the links. E.g., _why_ the links for manpage corrections go to the upstream community. I guess we can fill out more in the `about` field, but I'm not sure how ugly it will look to have a lot of text there.
  - I think I see where you are going with the "Downloads not working" link: if we give people specific direction rather than a catch-all, they are more likely to read the links and find the right spot. However, I do think that "Downloads not working" is almost never a problem on our site, since we don't host any of them ourselves. Still, we are probably the best place to start an issue, and we can direct people from there.
  - I'm not really a fan of PR templates, as it's just cruft I have to remove before writing my real PR message. But then, I don't seem to have much problem with writing long, descriptive PR messages or templates. ;) I'm OK leaving it if others find it useful, or think it may encourage drive-by contributors to be a bit more verbose.

**Comment by peff** [comment]
> Some random thoughts:

I'm inclined to merge this and iterate further from there if needed, but I'll leave it for a bit in case you'd like to change anything in response.

**Comment by HonkingGoose** [comment]
> Thanks, this is so much better!

Cool!

> I do wish there were more space to explain the situation for some of the links. E.g., _why_ the links for manpage corrections go to the upstream community. I guess we can fill out more in the `about` field, but I'm not sure how ugly it will look to have a lot of text there.

I'll go make a really large about field on my throwaway repo, so that we can see if we like that or not.

> I think I see where you are going with the "Downloads not working" link: if we give people specific direction rather than a catch-all, they are more likely to read the links and find the right spot. However, I do think that "Downloads not working" is almost never a problem on our site, since we don't host any of them ourselves. Still, we are probably the best place to start an issue, and we can direct people from there.

This is not something new, you already had a `downloads.md` file that gets you this "Downloads not working" link and text.
If you want to change it, we should change the frontmatter for the `downloads.md` file. 😉 

> I'm not really a fan of PR templates, as it's just cruft I have to remove before writing my real PR message. But then, I don't seem to have much problem with writing long, descriptive PR messages or templates. ;) I'm OK leaving it if others find it useful, or think it may encourage drive-by contributors to be a bit more verbose.

That's why I made the PR template really simple. 😄

**Comment by HonkingGoose** [comment]
Well, we can put a lot of extra text in the `about` field. 😄 👻 

Take a look at this: https://github.com/HonkingGoose/git-scm-template-preview/issues/new/choose

lots-of-text-in-about-field

**Comment by peff** [comment]
> This is not something new, you already had a downloads.md file that gets you this "Downloads not working" link and text.

Heh, I guess that goes to show how often I try to open an issue in this repo. :sweat_smile: I was thinking we still dumped people into the textarea directly (but we haven't since b78f624ca1ef598b9e68f5baaf573fe8227e3016). So this is a somewhat smaller change than I realized, but still IMHO a big improvement.

**Comment by peff** [comment]
> Well, we can put a lot of extra text in the about field.
 
Yeah, that doesn't look bad at all. The long line in the YAML is a bit ugly, but we can use the "folded" style to make it a little nicer. I just pushed up a commit with some extra wording that does that.

**Comment by HonkingGoose** [comment]
> The long line in the YAML is a bit ugly, but we can use the "folded" style to make it a little nicer. I just pushed up a commit with some extra wording that does that.

I can confirm that the "folded" style works properly on my throwaway repository issue chooser. 👍 

Feel free to make further changes to the `about` fields if needed before merging. 😄

**Comment by peff** [comment]
> I can confirm that the "folded" style works properly on my throwaway repository issue chooser.

Yeah, I checked it on a throwaway myself. :)

> Feel free to make further changes to the `about` fields if needed before merging.

I think I'll leave it at that for now. I had planned to add more to a few of the others, but once I tried, I found it was not an improvement!

So I'll merge, but if anybody has further suggestions, we can revisit in a separate PR. Thanks for working on this!

**Comment by HonkingGoose** [comment]
Thank you for merging in my work! ✨

**Pull request merged**
