### PR TITLE
Added a new Book and Turorial

### PR DESCRIPTION
**Pull request by packtpartner**
Added a new book (Git: Mastering Version Control) and tutorial (Git: Version Control Made Easy)

### CODE REVIEW

**Comment by peff** [comment]
I think the book link is OK (though it would probably look better if moved to the left-hand column, since that is the shortest one right now).

I'm not sure about the tutorial, though. The rest of the tutorial section are all short-ish documents that are free online. Mixing in a longer, paid training course feels out of place. I'm undecided on whether it should go in a separate section for paid training, or if it should be omitted entirely. Obviously we link to for-profit books already, but I'm not sure to what degree we want to get into advertising other resources.

**Comment by jnareb** [comment]
Actually "Git: Mastering Version Control" is a book bundle, composed of three books:

* _Git Essentials_, Ferdinando Santacroce
* _Git Version Control Cookbook_, Aske Olsson and Rasmus Voss
* _Mastering Git_, Jakub Narębski

Though it is presented similar to a book... Just FYI.

**Comment by packtpartner** [comment]
Would it help if I create a new section for paid courses? I think it could prove to be a good resource to help many in their learning of Git.

**Comment by stefanbeller** [comment]
> Would it help if I create a new section for paid courses?

I dunno. On the one hand it is better than mixing it into the section of un-paid courses, but on the other hand we'd need to discuss what to add (or remove) to such a list. Specially when money is involved, I think the Git community wants to not endorse one book and not endorse another one, but rather keep it fair. And from that POV it is easiest to just say no-no to any paid courses to not have to deal with the consequences later. (Not speaking for the community here, but just my own opinion).

That said, git-scm is not really in control by 'the git community' IMHO, but some GitHub guys. So if they will deal with the consequences later, I don't care.

**Comment by peff** [comment]
@jnareb Thanks. I think it's still appropriate to go into the book section (though I wonder if we should pick just one of "Mastering Git" and the bundle to display, if one is a superset of the other).

**Comment by peff** [comment]
> Would it help if I create a new section for paid courses? I think it could prove to be a good resource to help many in their learning of Git.

FYI, I took this to the upstream list to get opinions ([link]( http://public-inbox.org/git/CAP8UFD3Z9ZrLEZVkgL7ACkL5nOsoo2R6dUC=Bfy1AjF_9+4snQ@mail.gmail.com/)). I'm inclined to say that yes, a new section is OK, and other people with paid tutorial content would be welcome to submit PRs to add it. If it becomes overwhelming, then we'll deal with it at that point.

**Comment by peff** [comment]
> That said, git-scm is not really in control by 'the git community' IMHO, but some GitHub guys. So if they will deal with the consequences later, I don't care.

This is not quite true anymore. The site was more or less maintainer-less as early 2016, so I've tried to pick up the slack and deal with open PRs. I have rights on the GitHub repo and the Heroku deployment. I can add people to the former if anybody wants to get involved, but I think not easily to the latter (it's bundled with and paid for as part of GitHub's Heroku deployments).

Moreover, the site has been the de-facto official Git web page for a long time, and is more officially so in the last year. As a member project of the Software Freedom Conservancy, we need it to conform to a few non-profit rules, like not promoting one commercial interest over the other (and if it fails that, we either need to fix it, or make it clear that the page is not endorsed by the project).

I plan to bring this up as a topic at the Contributor Summit next week (and on the mailing list).

**Comment by packtpartner** [comment]
> I'm inclined to say that yes, a new section is OK, and other people with paid tutorial content would be welcome to submit PRs to add it. 
@peff thanks for clarifying. I will make the necessary changes as suggested.

**Comment by peff** [comment]
@packtpartner Sorry, this got lost in the flurry of recent activity on the site. The courses section you added looks good, and I don't see any reason not to merge.

**Comment by packtpartner** [comment]
Thanks a lot @peff

**Pull request merged**
