### PR TITLE
Rename figure

### PR DESCRIPTION
**Pull request by ben**
Fixes the issue reported at https://github.com/progit/progit2/pull/250#issuecomment-72939678.

### CODE REVIEW

**Comment by ben** [comment]
Ping! /cc @schacon

**Comment by jnavila** [comment]
:+1:

**Comment by ben** [comment]
Is it just me, or is [the page](http://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows#Centralized-Workflow) not fixed?

image

**Comment by jnavila** [comment]
It is not just you. In fact, other changes on the repo ( e.g. #514) were not deployed. :disappointed:

**Comment by ben** [comment]
Ping @schacon, @nickh, @peff, @jasonlong – anybody know how to get these fixes deployed?

**Comment by peff** [comment]
Sorry, I don't know. I've had changes take a while go to out, too, so I guess there's some manual workflow, but I don't know who kicks it off (I'd have guessed @bry4n or @schacon).

**Comment by jasonlong** [comment]
I haven't deployed anything here in quite a while. AFAIK @bry4n has been handling these things.

**Comment by bry4n** [comment]
Sorry, I thought we used an automatic deployment. The [latest master](https://github.com/git/git-scm.com/commit/33c35f69a69f3ef3285cdd0919b9ef038cd34f63) is deployed now! :+1:

**Comment by jnavila** [comment]
:cry: Still the [figure](http://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows#Centralized-Workflow)  is missing...

**Pull request merged**
