### PR TITLE
fix filename centralized_workflow.png

### PR DESCRIPTION
**Pull request by julianladisch**
Figure 1-2 and Figure 5-1 are missing on

https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control
https://git-scm.com/book/en/v2/Distributed-Git-Distributed-Workflows

because the images

https://github.com/progit/progit2/blob/master/book/01-introduction/images/centralized.png
https://github.com/progit/progit2/blob/master/book/05-distributed-git/images/centralized_workflow.png

have swapped their filenames:

https://github.com/git/git-scm.com/blob/master/public/book/en/v2/book/01-introduction/images/centralized_workflow.png
https://github.com/git/git-scm.com/blob/master/public/book/en/v2/book/05-distributed-git/images/centralized.png

This pull request renames the files and fixes
https://github.com/git/git-scm.com/issues/540
https://github.com/git/git-scm.com/issues/616
https://github.com/git/git-scm.com/issues/633
https://github.com/git/git-scm.com/issues/651
https://github.com/progit/progit2/issues/315
https://github.com/progit/progit2/issues/335
https://github.com/progit/progit2/issues/434
https://github.com/progit/progit2/issues/495
https://github.com/progit/progit2-ja/issues/82

### CODE REVIEW

**Comment by jnavila** [comment]
:+1: At least we can change this on the site

**Comment by harupong** [comment]
The git-scm.com site hasn't been updated yet, as manual deployment [seems required](https://github.com/git/git-scm.com/pull/505#issuecomment-98022554).

@bry4n Could you deploy the latest master to heroku?

**Comment by anbestephen** [comment]
@jnavila  I think this change has caused  Figure 1-2 under [Centralized-Version-Control-Systems](https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control#Centralized-Version-Control-Systems) to be missed. Could you talk a look at this please?

**Comment by jnavila** [comment]
@anbestephen It was already broken. The intended fix was not deployed so it is still broken. We have some big deployment issues here... :disappointed:

**Comment by YueLinHo** [comment]
I confirm en, zh, fr, jp version that it has been fixed.

**Comment by jnavila** [comment]
:tada:

**Pull request merged**
