### PR TITLE
Close the current dropdown TAB when you click another.

### PR DESCRIPTION
**Pull request by zhangenming**
## Changes

-

## Context

For a better experience

### CODE REVIEW

**Comment by pedrorijo91** [comment]
hi @zhangenming ! can you please share some printscreens of previous and new behavior please? just to make sure we understand what you are trying to achive

**Comment by jnavila** [comment]
I guess that: 

image

**Comment by zhangenming** [comment]
> I guess that:
> 

thanks..  this is it..
And most of that, when you click "Topics" tab, then click "English" tab, will trouble you

**Review by pedrorijo91 — APPROVED** [review]

**Comment by adsingh14** [comment]
@pedrorijo91 Is that suppose to work like this ?
Every dropdown stays open instead of collapsing.

image

**Comment by adsingh14** [comment]
> 
> thanks.. this is it.. And most of that, when you click "Topics" tab, then click "English" tab, will trouble you

@zhangenming Is it supposed to close the another dropdown ?

image

**Comment by adsingh14** [comment]
> 
> thanks.. this is it.. And most of that, when you click "Topics" tab, then click "English" tab, will trouble you

@zhangenming @pedrorijo91  Is it supposed to close the another dropdown or keep it open ?

image

**Pull request merged**
