### PR TITLE
Remove windows-setup auto download functionality

### PR DESCRIPTION
**Pull request by adsingh14**
## Changes

- Removed extra lines used on Windows download page.
- Removed auto-download function/method from `.js` file.

## Context

CC: https://github.com/git/git-scm.com/pull/1655#issuecomment-993520669

### CODE REVIEW

**Review by pedrorijo91 — APPROVED** [review]
sorry for taking some time, but overall this LGTM

**Comment by pedrorijo91** [comment]
if anyone with windows machine can test things look good as well it would be great. this version is deployed at https://git-scm-pr-1660.herokuapp.com/download/win

**Comment by adsingh14** [comment]
@pedrorijo91 One more thing (not related with this issue but readability): What if we make `<code>` tag content bold or add some padding space around it ?

Current: 
image

Expected:
image

**Comment by adsingh14** [comment]
@pedrorijo91 Thanks for merging PR. 

Was this [function](https://github.com/git/git-scm.com/blob/main/app/assets/javascripts/application.js#L243) written for Windows page?

**Comment by pedrorijo91** [comment]
seems to have been introduced at https://github.com/git/git-scm.com/pull/1418

**Comment by adsingh14** [comment]
It seems that we don't need that method now ?

**Comment by adsingh14** [comment]
Alright! I will amend this commit to keep download code in a single repo.

**Comment by adsingh14** [comment]
> regarding the font-weight, i'd say to feel free to submit a PR and we can see how it looks on the deployment! 😁

Here's the current output:
image
Expected:
image

Though `<code>` tag is used on every page so apply this on 'downloads' pages only.

**Pull request merged**
