### PR TITLE
adding license information to gui clients page

### PR DESCRIPTION
**Pull request by alpreu**
Created a new PR as explained by @pedrorijo91 in #1030. Thanks for your help 👍

### CODE REVIEW

**Comment by pedrorijo91** [comment]
as discussed on https://github.com/git/git-scm.com/pull/1030#issuecomment-335030069, we will try to ping the original authors (using git blame) and perhaps the tools developers so that they can have  a chance to respond

**Comment by pedrorijo91** [comment]
git blame is not very useful due to https://github.com/git/git-scm.com/commit/b9b5595c015986d0223e0f8b3b94db8f4dd5ca93, had to check the file history (https://github.com/git/git-scm.com/commits/master/app/views/downloads/guis/index.html.haml) . 

guis (from https://git-scm.com/downloads/guis):

| gui | blame author username  | has reviewed? |
|-----|--------------|-------------|
| sourcetree |              |             |
| github desktop |     Croydon         |             |
| tortoiseGit |      csware        |             |
|  gitkraken  |      smith-kyle        |             |
|  gitup   |       swisspol       |             |
|  smartgit   |              |             |
|   git extensions   |              |             |
|  tower   |       gntr       |             |
|  gitg   |       cveneziani       |             |
|    gitX-dev  |     welladamm         |             |
| aurees    |      ychetyrko        |             |
|   git-cola  |              |             |
|  ungit   |      zigarn        |             |
|  gitbox   |       kheyse       |             |
|  Cycligent Git Tool   |      tylerc        |             |
|  GitEye   |      markphip        |             |
|  Fork   |     DanPristupov         |             |
|   GitAhead  |     hackhaslam         |             |
|  giggle   |     cveneziani         |             |
|   codeReview  |      FabriceSalvaire        |             |

some guis have missing authors because it were imported by Scott at the beginning.

I think I will just make them a mention in the next comment, asking for a review

**Comment by pedrorijo91** [comment]
to: @Croydon @csware @smith-kyle @swisspol @gntr @cveneziani @welladamm @ychetyrko @zigarn @kheyse @tylerc @markphip @DanPristupov @hackhaslam @FabriceSalvaire

Hey,

As many of you may know, the git-scm website lists many git GUI tools under https://git-scm.com/downloads/guis

As discussed in #381 , we pretend to add license information to the listed GUI tools. @alpreu made an awesome contribution by gathering the data in this PR. We thought you guys may wanted to have a look before merging this.

Let us know if any question arises! :)

**Comment by swisspol** [comment]
Looks good, thanks!

**Comment by pedrorijo91** [comment]
I decided to email/slack/irc a few to try getting faster answers. On one side it's a problem because it's not public info (it's on my email, maybe I should have cc git mailing list...), on the other side, I think there's no big problem. If someone eventually disagrees, it just needs to raise an issue/PR and we will take of it quickly

**Comment by tylerchurch** [comment]
Cycligent Git Tool developer here - LGTM!

**Comment by nacho** [comment]
Gitg looks good to me

**Comment by Silone** [comment]
Tower Team here: Great PR & Info is fine - Thanks!

**Comment by peff** [comment]
Thanks for putting together the table, @pedrorijo91. For the last few that don't have a reviewed entry, it's pretty easy to turn up their licenses:

  - git-cola: https://git-cola.github.io/license.html
  - gitextensions: https://github.com/gitextensions/gitextensions/blob/master/LICENSE.md
  - giggle: https://github.com/GNOME/giggle/blob/master/COPYING
  - smartgit: https://www.syntevo.com/smartgit/license.html
  - sourcetree: https://community.atlassian.com/t5/Sourcetree-questions/is-sourcetree-free/qaq-p/425664 
  - aurees: https://aurees.com/legal/license-agreement
  - gitX-dev: https://github.com/rowanj/gitx/blob/master/COPYING

all of which match the contents of the PR. So I think we are good here. Thanks everyone for your responses!

**Pull request merged**
