### PR TITLE
index.rake: build MyFirstContribution tutorial

### PR DESCRIPTION
**Pull request by peff**
This will be in the upcoming v2.23, and is in the same general ballpark as
SubmittingPatches. Since the release isn't out yet, this patch doesn't
do anything, but committing it now means it will kick in automatically
when v2.23 releases on Friday.

### CODE REVIEW

**Comment by peff** [comment]
You can test this by making a fake `v2.23.0` tag in your local git repo, then doing a `GIT_REPO=/path/to/local/repo rake local_index`. That should make `https://localhost:5000/docs/MyFirstContribution` work.

**Comment by jnavila** [comment]
Put aside styling of more advanced asciidoc structures (note blocks), :+1:

**Comment by peff** [comment]
Heh, I just quickly eyeballed the result and didn't notice the Note blocks. I agree they're not great, but they're not so horrible that you can't figure out what's going on. And in fact, it's nothing new. Look at the `note` at the top of https://git-scm.com/docs/git-prune, for example. Reading the asciidoc manual, it looks like these are supposed to have a nice icon in the left-hand side of the table, which is getting beyond a simple css tweak.

So I think I'll leave the styling for another day.

**Comment by peff** [comment]
Hmm, actually it looks like these blocks _should_ be styled, via https://github.com/git/git-scm.com/blob/44bf76690960f83c6cbf2451b07210b1b3ee40ae/app/assets/stylesheets/man-pages.scss#L74-L91.

But they don't seem to be. I wonder why.

**Comment by peff** [comment]
> I wonder why.

Wonder no more: #1363

**Pull request merged**
