### PR TITLE
Handle colliding anchors in documentation pages

### PR DESCRIPTION
**Pull request by samccone**
BUG=#1729

## Changes

Addresses #1729

### CODE REVIEW

**Review by pedrorijo91 — APPROVED** [review]
so we basically just append an index now to duplicated anchors, correct?

**Comment by samccone** [comment]
That is correct, each colliding anchor now gets -1 appended until no further collusions are encountered.

**Comment by samccone** [comment]
Thank you for the review.

**Comment by peff** [comment]
One downside with this approach is that it means the anchors aren't stable. If a new colliding one is introduced, then the original one may get "bumped" to be `-1`. But I don't think it's making anything _worse_ in that regard, and in the meantime is fixing a real problem. And I think making stable, unique anchors may be quite tricky. So it's definitely worth going with this for now.

**Comment by peff** [comment]
> And I think making stable, unique anchors may be quite tricky.

Just looking at this specific example, the first one probably should be `merge--ort--ours` (the option to the `ort` strategy), and the second one `merge--ours` (the actual `ours` strategy). But doing that by munging HTML with a regex is tricky. I think doing it right would probably involve writing a function to plug in to asciidoctor's extension mechanism, and which could see the parsed AST of the document. An alternative would be to actually parse the HTML with nokogiri or similar, and modify it there (we already do some nokogiri tricks on the book HTML, I think, but the manpage side is all hacky regexes).

**Pull request merged**
