### PR TITLE
git-scm redesign: review app

### PR DESCRIPTION
**Pull request by pedrorijo91**

### CODE REVIEW

**Comment by pedrorijo91** [comment]
the deploy failed. Does this mean anything to you @jasonlong ? I can try to have a look tomorrow

```
-----> Ruby app detected
-----> Compiling Ruby/Rails
-----> Using Ruby version: ruby-2.4.2
-----> Installing dependencies using bundler 1.15.2
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       Fetching gem metadata from https://rubygems.org/........
       Fetching version metadata from https://rubygems.org/..
       Fetching dependency metadata from https://rubygems.org/.
       Fetching rake 12.3.0
       Fetching concurrent-ruby 1.0.5
       Fetching minitest 5.11.3
       Installing minitest 5.11.3
       Installing rake 12.3.0
       Installing concurrent-ruby 1.0.5
       Fetching thread_safe 0.3.6
       Installing thread_safe 0.3.6
       Fetching builder 3.2.3
       Installing builder 3.2.3
       Fetching erubis 2.7.0
       Fetching mini_portile2 2.3.0
       Fetching crass 1.0.3
       Installing mini_portile2 2.3.0
       Installing erubis 2.7.0
       Installing crass 1.0.3
       Fetching rack 1.6.9
       Fetching mini_mime 1.0.0
       Installing rack 1.6.9
       Installing mini_mime 1.0.0
       Fetching arel 6.0.4
       Installing arel 6.0.4
       Fetching public_suffix 3.0.2
       Installing public_suffix 3.0.2
       Fetching ansi 1.5.0
       Fetching asciidoctor 1.5.6.1
       Installing ansi 1.5.0
       Using bundler 1.15.2
       Fetching diff-lcs 1.3
       Installing diff-lcs 1.3
       Fetching unf_ext 0.0.7.5
       Installing asciidoctor 1.5.6.1
       Fetching multipart-post 2.0.0
       Installing multipart-post 2.0.0
       Fetching hashr 0.0.22
       Installing hashr 0.0.22
       Installing unf_ext 0.0.7.5 with native extensions
       Fetching iso8601 0.10.1
       Installing iso8601 0.10.1
       Fetching json 2.1.0
       Installing json 2.1.0 with native extensions
       Fetching kgio 2.11.2
       Installing kgio 2.11.2 with native extensions
       Fetching mime-types 2.99.3
       Installing mime-types 2.99.3
       Fetching multi_json 1.13.1
       Installing multi_json 1.13.1
       Fetching netrc 0.11.0
       Installing netrc 0.11.0
       Fetching pg 0.21.0
       Installing pg 0.21.0 with native extensions
       Fetching rack-timeout 0.4.2
       Installing rack-timeout 0.4.2
       Fetching thor 0.19.4
       Installing thor 0.19.4
       Fetching rails_serve_static_assets 0.0.5
       Installing rails_serve_static_assets 0.0.5
       Fetching rails_stdout_logging 0.0.5
       Installing rails_stdout_logging 0.0.5
       Fetching raindrops 0.19.0
       Installing raindrops 0.19.0 with native extensions
       Fetching redcarpet 3.4.0
       Installing redcarpet 3.4.0 with native extensions
       Fetching redis 4.0.1
       Installing redis 4.0.1
       Fetching rubyzip 1.2.1
       Installing rubyzip 1.2.1
       Fetching tilt 2.0.8
       Installing tilt 2.0.8
       Fetching yajl-ruby 1.3.1
       Installing yajl-ruby 1.3.1 with native extensions
       Fetching tzinfo 1.2.5
       Installing tzinfo 1.2.5
       Fetching i18n 0.9.5
       Installing i18n 0.9.5
       Fetching nokogiri 1.8.2
       Installing nokogiri 1.8.2 with native extensions
       Fetching mail 2.7.0
       Installing mail 2.7.0
       Fetching rack-test 0.6.3
       Installing rack-test 0.6.3
       Fetching rack-proxy 0.6.3
       Fetching sprockets 3.7.1
       Installing rack-proxy 0.6.3
       Installing sprockets 3.7.1
       Fetching addressable 2.5.2
       Installing addressable 2.5.2
       Fetching faraday 0.14.0
       Installing faraday 0.14.0
       Fetching unf 0.1.4
       Fetching rails_12factor 0.0.3
       Installing unf 0.1.4
       Installing rails_12factor 0.0.3
       Fetching unicorn 5.4.0
       Fetching redis-store 1.4.1
       Installing redis-store 1.4.1
       Installing unicorn 5.4.0 with native extensions
       Fetching activesupport 4.2.10
       Installing activesupport 4.2.10
       Fetching launchy 2.4.3
       Installing launchy 2.4.3
       Fetching faraday_middleware 0.12.2
       Installing faraday_middleware 0.12.2
       Fetching sawyer 0.8.1
       Installing sawyer 0.8.1
       Fetching domain_name 0.5.20170404
       Installing domain_name 0.5.20170404
       Fetching redis-rack 2.0.4
       Installing redis-rack 2.0.4
       Fetching rails-deprecated_sanitizer 1.0.3
       Installing rails-deprecated_sanitizer 1.0.3
       Fetching globalid 0.4.1
       Installing globalid 0.4.1
       Fetching activemodel 4.2.10
       Installing activemodel 4.2.10
       Fetching redis-activesupport 5.0.4
       Installing redis-activesupport 5.0.4
       Fetching octokit 4.8.0
       Installing octokit 4.8.0
       Fetching http-cookie 1.0.3
       Installing http-cookie 1.0.3
       Fetching activejob 4.2.10
       Installing activejob 4.2.10
       Fetching activerecord 4.2.10
       Installing activerecord 4.2.10
       Fetching rest-client 1.8.0
       Installing rest-client 1.8.0
       Fetching tire 0.6.2
       Installing tire 0.6.2
       Fetching rails-dom-testing 1.0.9
       Fetching loofah 2.2.0
       Installing loofah 2.2.0
       Installing rails-dom-testing 1.0.9
       Fetching rails-html-sanitizer 1.0.3
       Installing rails-html-sanitizer 1.0.3
       Fetching actionview 4.2.10
       Installing actionview 4.2.10
       Fetching actionpack 4.2.10
       Installing actionpack 4.2.10
       Fetching actionmailer 4.2.10
       Fetching railties 4.2.10
       Installing actionmailer 4.2.10
       Installing railties 4.2.10
       Fetching sprockets-rails 3.2.1
       Installing sprockets-rails 3.2.1
       Fetching redis-actionpack 5.0.2
       Installing redis-actionpack 5.0.2
       Fetching redis-rails 5.0.2
       Installing redis-rails 5.0.2
       Fetching rails 4.2.10
       Fetching webpacker 3.2.2
       Installing webpacker 3.2.2
       Installing rails 4.2.10
       Bundle complete! 38 Gemfile dependencies, 77 gems now installed.
       Gems in the groups development and test were not installed.
       Bundled gems are installed into ./vendor/bundle.
       Post-install message from tire:
       ================================================================================
       Please check the documentation at <http://karmi.github.com/retire/>.
       --------------------------------------------------------------------------------
       IMPORTANT CHANGES LATELY:
       19e524c [ACTIVEMODEL] Exposed the response from `MyModel#.update_index` as the `response` method on return value
       bfcde21 [#916] Added support for the Suggest API (@marc-villanueva)
       710451d [#857] Added support for the Suggest API (@fbatista)
       See the full changelog at <http://github.com/karmi/tire/commits/v0.6.2>.
       --------------------------------------------------------------------------------
       Bundle completed (56.20s)
       Cleaning up the bundler cache.
       Warning: the running version of Bundler (1.15.2) is older than the version that created the lockfile (1.16.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
       The latest bundler is 1.16.1, but you are currently running 1.15.2.
       To update, run `gem install bundler`
-----> Installing node-v6.11.1-linux-x64
-----> Installing yarn-v1.0.2
-----> Detecting rake tasks
-----> Preparing app for Rails asset pipeline
       Running: rake assets:precompile
       ** Invoke assets:precompile (first_time)
       ** Invoke assets:environment (first_time)
       ** Execute assets:environment
       ** Invoke environment (first_time)
       ** Execute environment
       ** Execute assets:precompile
       rake aborted!
       LoadError: cannot load such file -- sass
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/autoload/sass.rb:1:in `<top (required)>'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `block in require'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:240:in `load_dependency'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.10/lib/active_support/dependencies.rb:274:in `require'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/sass_compressor.rb:44:in `initialize'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/sass_compressor.rb:24:in `new'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/sass_compressor.rb:24:in `instance'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/sass_compressor.rb:28:in `call'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:75:in `call_processor'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `reverse_each'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/processor_utils.rb:56:in `call_processors'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:134:in `load_from_unloaded'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:60:in `block in load'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/loader.rb:44:in `load'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:20:in `block in initialize'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/cached_environment.rb:47:in `load'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:66:in `find_asset'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/base.rb:73:in `find_all_linked_assets'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:134:in `block in find'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `each'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:133:in `find'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/sprockets/manifest.rb:185:in `compile'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:68:in `block (3 levels) in define'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-3.7.1/lib/rake/sprocketstask.rb:147:in `with_logger'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/task.rb:67:in `block (2 levels) in define'
       /tmp/build_5454b5f10037b11085e2bde14a744056/git-git-scm.com-678fa76/vendor/bundle/ruby/2.4.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
       Tasks: TOP => assets:precompile
       (See full trace by running task with --trace)
 !
 !     Precompiling assets failed.
 !
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by jasonlong** [comment]
The sass and asset pipeline clues make me think it has to do with the changes @tarebyte helped put into place maybe?

**Comment by jasonlong** [comment]
@pedrorijo91 I totally forgot to open the PR for this branch. Would you prefer I open one so that I can keep the original comment body updated with the ongoing changes?

**Comment by pedrorijo91** [comment]
feel free to do as you find it easier/better @jasonlong :)

**Comment by jasonlong** [comment]
Ok, since the deployment doesn't work anyhow, I'll go ahead and close this and open a new one with some placeholder content that I'll keep updated along the way.

**Pull request closed without merging**
