### PR TITLE
More l10n manpages

### PR DESCRIPTION
**Pull request by jnavila**
This series reworks a little manpage l10n. Nothing fancy, but it's more usable.

### CODE REVIEW

**Comment by jnavila** [comment]
BTW, could someone set up the nightly builds of localized manpages?

**Comment by peff** [comment]
Looks good; linking to the same language from the topics menu makes perfect sense.

I'll kick off a `rake preindex_l10n` after merging this, and set it up to run nightly.

**Comment by peff** [comment]
OK, we're set up for nightly `preindex_l10n` runs now. The run I just did was a noop; looks like none of the new languages added here have been pushed to your repo yet.

**Comment by jnavila** [comment]
I'll push some updates soon.

**Comment by jnavila** [comment]
Done.

**Comment by peff** [comment]
Nice. I kicked off a manual `l10n` run, if you want to peek at the output.

**Comment by jnavila** [comment]
Thanks a lot. The fixups are applied, the new page is here... Looks good! :tada:

**Pull request merged**
