### PR TITLE
progit2: fix internal book links

### PR DESCRIPTION
**Pull request by jnavila**
Internal book links url can have any form in "chapter#link"

### CODE REVIEW

**Comment by pedrorijo91** [comment]
for the record, some of the broken links can be observed at:

* https://git-scm.com/book/en/v2/Git-Basics-Getting-a-Git-Repository
* https://git-scm.com/book/en/v2/Git-Basics-Recording-Changes-to-the-Repository

and probably many more.

**Comment by jnavila** [comment]
I tested locally and this seems to fix it. The initial regexp was too selective. I'll push this and see what happens (there's a need for the script to run another time, even if the content hasn't changed).

**Comment by peff** [comment]
After rebuilding with `GENLANG=en rake remote_genbook2`, the links at those pages seem fixed. Do the other languages need rebuilt, too?

**Comment by jnavila** [comment]
Normally, no. I was planning to merge an equivalent shift for the French translation (AFAIK, the only other language making the transition), but it's better to postpone it  a little.

**Pull request merged**
